spring:
  profiles:
    include: oauth

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  session:
    store-type: jdbc

  h2:
    console:
      enabled: true

server:
  servlet:
    encoding:
      force-response: true
